version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodejs-server-cicd
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
# DownloadBundle:
# BeforeInstall:
# Install:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
# ValidateService:
